export const asgr_phrases = [
  'Off to slay some bloodsuckers with my Asgardian squad!',
  "As the God of Thunder, I'm always up for a vampire hunt with my friends.",
  "Just another day in Asgard, hunting vampires like it's nobody's business.",
  'Time to show those bloodsuckers what Asgardians are made of!',
  'Vampire hunting is just our way of showing off our Asgardian strength.',
  'Who needs garlic when you have Asgardian warriors by your side?',
  'Taking down vampires with the power of Asgard behind us!',
  "The vampires won't know what hit them when the Asgardians come knocking.",
  'Vampires beware, the Asgardians are on the hunt!',
  'Asgardian friends and vampire hunting – a match made in Valhalla.',
  'Off to vanquish some bloodsuckers with my fellow Asgardians.',
  "As long as we have our Asgardian strength, vampires don't stand a chance.",
  "The vampires won't know what hit them when they face the might of Asgard.",
  'Vampire hunting with a touch of Asgardian flair – nothing can stop us.',
  'Just a casual day for us Asgardians – hunting vampires and taking names.',
  'Brace yourselves vampires, the Asgardians are coming for you!',
  'Who needs stakes when you have Asgardian friends to take down vampires?',
  'Asgardian friends and vampire hunting – a winning combination.',
  "With the power of Asgard behind us, vampires don't stand a chance.",
  "Vampires might be immortal, but they're no match for the Asgardians.",
  'Off to stake some vampires with my Asgardian crew – no big deal.',
  'Vampires, prepare to face the wrath of the Asgardians.',
  "As the God of Mischief, I can't resist a good vampire hunt with my Asgardian pals.",
  'Vampires may be creatures of the night, but Asgardians bring the thunder.',
  'Vampires beware, Asgardian friends are on the prowl.',
  'Hunting vampires with my Asgardian comrades – just another Tuesday.',
  "Vampires may be intimidating, but they're no match for the mighty Asgardians.",
  'Who needs silver bullets when you have Asgardian warriors on your side?',
  'Vampire hunting is just another way for Asgardians to show off their skills.',
  'Off to slay some bloodsuckers with my Asgardian amigos – wish us luck!',
  "Vampires may be swift, but they can't outrun the power of Asgard.",
  'Vampire hunting with Asgardian friends – the ultimate team-up.',
  'Asgardians and vampires – a match made in mythological heaven.',
  "Vampires may be immortal, but they're no match for Asgardian strength.",
  "As heimdall watches over Asgard, we're off to hunt some vampires.",
  'Vampires may have fangs, but Asgardians have the power of the gods.',
  "With Asgardian friends by my side, vampires don't stand a chance.",
  'Asgardian friends and vampire hunting – a legendary combination.',
  'Time to put our Asgardian strength to the test against the undead.',
  'Vampires beware – the Asgardians are coming for you, stakes and all!',
];

export const kik_phrases = [
  'You guys are just sitting around waiting for vampires to come to us? Unbelievable!',
  "I didn't become the God of Thunder to watch you all lounge around like lazy kettles!",
  'Do you honestly expect the vampires to just waltz into Asgard and introduce themselves?',
  'Even Mjolnir is shaking its head at your lack of effort.',
  'I swear, if I catch one more of you napping instead of vampire hunting...',
  'Is this a team of warriors or a bunch of couch potatoes?',
  "I can't believe I have to remind you all that vampires don't just walk up and knock on the door.",
  'Why am I surrounded by such a bunch of lazy lads and lasses?',
  "I'll give you all a two-minute head start before I unleash the full force of my wrath.",
  "If anyone needs me, I'll be out actually looking for vampires instead of dilly-dallying in the halls of Asgard.",
  "I feel like I'm the only one taking this vampire problem seriously!",
  "If we let the vampires win, it'll be an eternal shame on Asgard.",
  'Stop making excuses and start making stakes!',
  "Am I the only one who understands that vampires won't just show up at a dinner party uninvited?",
  "I can't believe I have to baby-sit you all like this.",
  'Seriously, am I the only one who actually read up on vampire hunting tactics?',
  "I didn't bust my butt training for this moment just to watch you all become slothful slobs.",
  "Maybe if you spent less time lounging around and more time hunting, we wouldn't have this vampire problem in the first place.",
  "I swear, it's like herding lazy goats with you lot.",
  "I haven't seen this level of laziness since Loki's last scheme.",
  "If you can't be bothered to help in the vampire hunt, then I don't want to hear your excuses!",
  "I'd tell you all to pull your weight, but I doubt you could lift Mjolnir.",
  "We're meant to be warriors, not glorified nap-takers.",
  "I won't rest until every last vampire is driven from Asgard, and neither should you!",
  'Stop trying to out-sleep each other and start trying to out-hunt the vampires!',
  'Do I have to spell it out for you? V-A-M-P-I-R-E-S!',
  "If the vampires see us lounging around, they'll think we're an easy target. Shape up!",
  "Vampires aren't going to knock on our doors and ask to be staked. We have to go find them!",
  'Do you want to be known as the Asgardians who let vampires overrun our realm?',
  "I'd say you're moving like molasses, but that would be an insult to molasses.",
  'I have half a mind to lock you all in a room with a vampire until you learn your lesson.',
  "If Odin were here, he'd be ashamed at the laziness infecting his warriors.",
  'Every minute you waste sitting around is a minute the vampires get stronger.',
  "It's time to wake up and smell the vampire blood, people!",
  'Since when did Asgardians become known for their lackadaisical approach to vampire hunting?',
  "I'll give you a gold star if you actually get off your backside and start searching for vampires.",
  "If I catch one more of you sleeping on the job, I'll consider it an act of treason against Asgard.",
  "Remember when we used to be known as fierce warriors? Let's get that reputation back by hunting some vampires!",
  "Being the God of Thunder isn't just about lightning and storms – it's about taking action and getting things done!",
  "If I have to babysit you all through this vampire hunt, I'll be sorely disappointed.",
  "I'll start calling you the Asgardian Snooze Brigade if you don't shape up!",
  'I am Thor, son of Odin, and I will not stand idly by while vampires threaten our realm!',
  "I've seen Frost Giants with more ambition than you lot.",
  "If you can't be bothered to fight for Asgard, then maybe it's time you reconsider your allegiance.",
  "Asgard needs warriors, not pillow fighters. Let's show these vampires what we're made of!",
  "The vampires aren't going to just announce themselves, you know. We have to go looking for them!",
];
