name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # или укажите ветку, на которую хотите реагировать

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_USER_PASSWORD }}
        strict: false
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        passphrase: ${{secrets.SSH_PASSPHRASE}}
        port: ${{ secrets.REMOTE_SERVER_PORT }}
        script: |
          cd /home/referral/wewetap-back
          git pull origin main
          docker-compose down
          docker-compose pull  # Обновление образов
          docker-compose up -d --build  # Перезапуск контейнеров
